### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by eprilx** [eprilx/FFDConverter#7]
> @Ezio-2005 @buhboyvjppro999 @PxpUii There is a tool for modding image/texture font whithout using these hex, it's [AnvilToolkit](https://www.nexusmods.com/assassinscreedbrotherhood/mods/21) created by Kamzik123. Thanks to @Mstr-Samuel for pointing that out.

Thank's for this but I have use this tool and And I managed to change the texture of the font, but the problem is still there
That is, when I edit the texture, and when I make the FFD font with your software, and when I put it in the game, the font is still displayed in a mess.

_Originally posted by @Ezio-2005 in https://github.com/eprilx/FFDConverter/issues/2#issuecomment-1783910556_

**Comment by eprilx** [comment]
Tell me more details:
- Which game ?
- What tools did you use ? Describe step by step how you worked with these tools.

**Comment by Ezio-2005** [comment]
So the game is: Assassin's creed brotherhood

First: I unpacked two forge files (DataPC.forge - DataPC_extra.foge)  with AnvilToolkit.
In the DataPC_extra.foge I was able to find font textures for example name of the one them was: 1_-_AC2Aaux_ProMedium_Latin_1_Map.TextureMap.  I changed the letters of that texture to my own language letters and after editing that texture, I repacked it to the game. again with AnvilToolkit.

Second: In the DataPC.forge, I was able to find the FFD fonts and I changed one of them with your tool and again I repacked it to the game with AnvilToolkit.

But after doing all of these, the font in the game is still messed up.

**Comment by Ezio-2005** [comment]
[Orginals.zip](https://github.com/eprilx/FFDConverter/files/13197637/Orginals.zip)
[Modified.zip](https://github.com/eprilx/FFDConverter/files/13197638/Modified.zip)

**Comment by eprilx** [comment]
For textures, use AnvilToolkit.
For FFD you must use the Delutto tool to unpack/repack, export/import (why ? the answer at #6)
Then try the following:
1 - Only edit FFD, do not edit textures. Check if it displays correctly or not in the game.
2 - Only edit textures, do not edit FFD. Check if it displays correctly or not in the game.

**Comment by Ezio-2005** [comment]
> For textures, use AnvilToolkit. For FFD you must use the Delutto tool to unpack/repack, export/import (why ? the answer at #6) Then try the following: 1 - Only edit FFD, do not edit textures. Check if it displays correctly or not in the game. 2 - Only edit textures, do not edit FFD. Check if it displays correctly or not in the game.

This is when I only edit FFD and the font still messed up.
![ACBSP 2023-10-29 14-34-19-618](https://github.com/eprilx/FFDConverter/assets/102662700/4ef84f64-e67a-430c-9834-1d2253bf6b0a)


And this is when I Only edit texture and the font still messed up and also the Text that I translated disappeared.
![ACBSP 2023-10-29 14-42-30-625](https://github.com/eprilx/FFDConverter/assets/102662700/387689f2-ecff-433f-bb3f-eae91c27e6a3)

**Comment by eprilx** [comment]
Next:
- Create new bitmap fonts that support ASCII languages ​​(Latin in bmfont)
- Do not edit localization files
- Use Anviltoolkit to edit textures
- Use Delutto's tools to edit FFD
- Repack/Import both file

**Comment by Ezio-2005** [comment]
> Next:
> 
> * Create new bitmap fonts that support ASCII languages ​​(Latin in bmfont)
> * Do not edit localization files
> * Use Anviltoolkit to edit textures
> * Use Delutto's tools to edit FFD
> * Repack/Import both file

You mean add only English Letters to the font? and not my own language letters?

**Comment by eprilx** [comment]
Yes, we need to test to find out what error is causing the font to display wrongly

**Comment by Ezio-2005** [comment]
![ACBSP 2023-10-29 21-12-14-180](https://github.com/eprilx/FFDConverter/assets/102662700/8254a2d5-3d91-4300-b6cc-a357433049c9)

Still messed up!

**Comment by eprilx** [comment]
> [Orginals.zip](https://github.com/eprilx/FFDConverter/files/13197637/Orginals.zip) [Modified.zip](https://github.com/eprilx/FFDConverter/files/13197638/Modified.zip)

Is it ACBr game?
My original file from cr*cked on steam pc is completely different from your original file.
The texture is 1024x1024 (yours is 512x1024). FFD after convert to fnt will have this line file="0x26bcff52" (yours is file="0xbb87a6c2")
[Original2.zip](https://github.com/eprilx/FFDConverter/files/13198983/Original2.zip)
<img width="695" alt="image" src="https://github.com/eprilx/FFDConverter/assets/49425492/088df362-5f61-41e7-8f21-27993d38ae8f">

**Comment by Ezio-2005** [comment]
Yeah it's AcBr
i have deluxe edition... but They should not be different....
it's strange...

**Comment by Ezio-2005** [comment]
I think I made some progress...
![ACBSP 2023-10-30 01-20-09-456](https://github.com/eprilx/FFDConverter/assets/102662700/23000f5a-6ea2-467d-aba7-7929a04bd387)

**Comment by Ezio-2005** [comment]
My problem fixed.
Thanks

**Comment by eprilx** [comment]
Can you share with me what you changed to make it work ?

**Comment by Ezio-2005** [comment]
I just made the FFD font with the right size (like the original FFD) and after editing texture with that Anvitool I was able to repack it to the game and it worked..

**Comment by eprilx** [comment]
What does "right size" mean? Width/height of texture when creating with Bmfont or "size" of font?

**Comment by Ezio-2005** [comment]
Yeah Width/Height
And I also changed the font size in bmfont to a bigger size....

**Comment by Ezio-2005** [comment]
> Understood! I will note this issue in the readme... But in general, the readme is still difficult to read and follow 😂... Thank you for your contribution.

Your welcome my brother, And thank you for your great tool

**Comment by Argon37** [comment]
Hi eprilx, can you give me some advice?
I have DODI version(based on steam version) of Assassin's Creed II.
I am creating my own font to translate the game into my language (Russian). I used your tool, BMFontGenerator tool and Ubisoft Data&Forge Deluto tool. In the game I can see all the translated text, but the letters overlap each other so much that the text is hard to read. I tried many fonts, many Padding and Slacing values ​​in BMFontGenerator (even 10), but the game just ignores it. Font sizes also do not affect the overlap (it does not get bigger or smaller when editing the font size). This mainly concerns the "8_-_AC2Aaux_ProMedium_Latin_1_MapDesc.data" font. In "14_-_AC2Aaux_ProLight_Latin_1_MapDesc.data" I have a better situation (minimal overlap):

![Image](https://github.com/user-attachments/assets/7e3f696a-ff87-4927-9a1f-d7ec4cff7858)

I also tried manually editing the kerning values ​​in the .fnt files before converting to .ffd, but that didn't change anything either.

**Comment by eprilx** [comment]
> Hi eprilx, can you give me some advice? I have DODI version(based on steam version) of Assassin's Creed II. I am creating my own font to translate the game into my language (Russian). I used your tool, BMFontGenerator tool and Ubisoft Data&Forge Deluto tool. In the game I can see all the translated text, but the letters overlap each other so much that the text is hard to read. I tried many fonts, many Padding and Slacing values ​​in BMFontGenerator (even 10), but the game just ignores it. Font sizes also do not affect the overlap (it does not get bigger or smaller when editing the font size). This mainly concerns the "8_-_AC2Aaux_ProMedium_Latin_1_MapDesc.data" font. In "14_-_AC2Aaux_ProLight_Latin_1_MapDesc.data" I have a better situation (minimal overlap):
> 
> ![Image](https://github.com/user-attachments/assets/7e3f696a-ff87-4927-9a1f-d7ec4cff7858)
> 
> I also tried manually editing the kerning values ​​in the .fnt files before converting to .ffd, but that didn't change anything either.

Edit config.xml then increase scaleXadvance

**Comment by Argon37** [comment]
> Edit config.xml then increase scaleXadvance

Thanks for your help, everything works now.

![Image](https://github.com/user-attachments/assets/7919f12a-f0ce-4477-8e31-fd715128edb6)
